version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
