version: '3.5'

services:
  dash:
    image: mauricenino/dashdot:latest
    container_name: dashdot
    restart: unless-stopped
    privileged: true
    ports:
      - '8040:3001'
    volumes:
      - /:/mnt/host:ro